In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.cross_validation import train_test_split

G:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

### Step 1  数据集导入

In [2]:
data_2 = pd.read_csv('iBeacon_RSSI_Labeled.csv')

In [3]:
data_2.head(5)

,location,date,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,10-18-2016 11:15:21,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
1,P01,10-18-2016 11:15:19,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
2,P01,10-18-2016 11:15:17,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
3,P01,10-18-2016 11:15:15,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
4,P01,10-18-2016 11:15:13,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200

In [4]:
print(data_2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1420 entries, 0 to 1419
Data columns (total 15 columns):
location    1420 non-null object
date        1420 non-null object
b3001       1420 non-null int64
b3002       1420 non-null int64
b3003       1420 non-null int64
b3004       1420 non-null int64
b3005       1420 non-null int64
b3006       1420 non-null int64
b3007       1420 non-null int64
b3008       1420 non-null int64
b3009       1420 non-null int64
b3010       1420 non-null int64
b3011       1420 non-null int64
b3012       1420 non-null int64
b3013       1420 non-null int64
dtypes: int64(13), object(2)
memory usage: 166.5+ KB
None

### Step 2  数据预处理

###### 2.1 删除无用列,替换无效值

In [5]:
#删除‘日期’列
del data_2['date']

In [6]:
print(data_2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1420 entries, 0 to 1419
Data columns (total 14 columns):
location    1420 non-null object
b3001       1420 non-null int64
b3002       1420 non-null int64
b3003       1420 non-null int64
b3004       1420 non-null int64
b3005       1420 non-null int64
b3006       1420 non-null int64
b3007       1420 non-null int64
b3008       1420 non-null int64
b3009       1420 non-null int64
b3010       1420 non-null int64
b3011       1420 non-null int64
b3012       1420 non-null int64
b3013       1420 non-null int64
dtypes: int64(13), object(1)
memory usage: 155.4+ KB
None

In [7]:
data_2.replace(-200,0,inplace = True)

In [8]:
data_2.head(10)

,location,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,0,0,0,0,0,-78,0,0,0,0,0,0,0
1,P01,0,0,0,0,0,-78,0,0,0,0,0,0,0
2,P01,0,0,0,0,0,-77,0,0,0,0,0,0,0
3,P01,0,0,0,0,0,-77,0,0,0,0,0,0,0
4,P01,0,0,0,0,0,-77,0,0,0,0,0,0,0
5,P01,0,0,-82,0,0,0,0,0,0,0,0,0,0
6,P01,0,0,-80,0,0,-77,0,0,0,0,0,0,0
7,P02,0,0,-86,0,0,0,0,0,0,0,0,0,0
8,R01,0,0,0,-75,0,0,0,0,0,0,0,0,0
9,R01,0,0,0,-75,0,0,0,0,0,0,0,0,0

###### 2.2 统计数据集中出现的不同 location 数目

In [9]:
loc_count={}
for i in data_2['location'].index:
    if data_2['location'][i] in loc_count:
        loc_count[data_2['location'][i]] += 1
    else:
        loc_count[data_2['location'][i]] = 1 

print(len(loc_count))

105

In [10]:
data_2.head(20)

,location,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,0,0,0,0,0,-78,0,0,0,0,0,0,0
1,P01,0,0,0,0,0,-78,0,0,0,0,0,0,0
2,P01,0,0,0,0,0,-77,0,0,0,0,0,0,0
3,P01,0,0,0,0,0,-77,0,0,0,0,0,0,0
4,P01,0,0,0,0,0,-77,0,0,0,0,0,0,0
5,P01,0,0,-82,0,0,0,0,0,0,0,0,0,0
6,P01,0,0,-80,0,0,-77,0,0,0,0,0,0,0
7,P02,0,0,-86,0,0,0,0,0,0,0,0,0,0
8,R01,0,0,0,-75,0,0,0,0,0,0,0,0,0
9,R01,0,0,0,-75,0,0,0,0,0,0,0,0,0
10,R01,0,0,0,-80,0,0,0,0,0,0,0,0,0
11,R01,0,0,0,-78,0,0,0,0,0,0,0,0,0
12,R01,0,0,0,-78,0,0,0,0,0,0,0,0,0
13,R02,0,0,0,-78,0,0,0,0,0,0,0,0,0
14,R02,0,0,0,-76,0,0,0,0,0,0,0,0,0
15,R02,0,0,0,-78,0,0,0,0,0,0,0,0,0
16,R02,0,0,0,-74,0,0,0,0,0,0,0,0,0
17,R02,0,0,0,-76,0,0,0,0,0,0,0,0,0
18,R02,0,0,0,-72,0,0,0,0,0,0,0,0,0
19,R02,0,0,0,-78,0,0,0,0,0,0,0,0,0

In [11]:
print(loc_count)

{'O02': 8, 'P01': 13, 'P02': 6, 'R01': 14, 'R02': 18, 'S01': 23, 'S02': 21, 'T01': 4, 'U02': 10, 'U01': 8, 'J03': 24, 'K03': 23, 'L03': 13, 'M03': 12, 'N03': 14, 'O03': 13, 'P03': 12, 'Q03': 18, 'R03': 15, 'S03': 17, 'T03': 6, 'U03': 14, 'U04': 10, 'T04': 12, 'S04': 18, 'R04': 10, 'Q04': 18, 'P04': 13, 'O04': 24, 'N04': 10, 'M04': 19, 'L04': 20, 'K04': 34, 'J04': 32, 'I04': 18, 'I05': 19, 'J05': 19, 'K05': 25, 'L05': 14, 'M05': 10, 'N05': 12, 'O05': 24, 'P05': 12, 'Q05': 24, 'R05': 16, 'S05': 20, 'T05': 10, 'U05': 8, 'S06': 20, 'R06': 6, 'Q06': 4, 'P06': 8, 'O06': 15, 'N06': 14, 'M06': 20, 'L06': 22, 'K06': 22, 'J06': 29, 'I06': 27, 'F08': 4, 'J02': 22, 'J07': 27, 'I07': 27, 'I10': 14, 'J10': 6, 'D15': 14, 'E15': 4, 'G15': 4, 'J15': 8, 'L15': 10, 'R15': 12, 'T15': 7, 'W15': 17, 'I08': 26, 'I03': 19, 'J08': 9, 'I01': 18, 'I02': 21, 'J01': 16, 'K01': 6, 'K02': 9, 'L01': 6, 'L02': 10, 'M01': 10, 'M02': 14, 'N01': 12, 'N02': 12, 'O01': 2, 'I09': 8, 'D14': 4, 'D13': 6, 'K07': 11, 'K08': 12, 'N15': 12, 'P15': 7, 'I15': 5, 'S15': 3, 'U15': 5, 'V15': 8, 'S07': 10, 'S08': 4, 'L09': 2, 'L08': 3, 'Q02': 4, 'Q01': 6}

###### 2.3 将105个位置映射成数字，方便模型进行数据处理

In [12]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le.fit(data_2['location'])
data_2['location'] = le.transform(data_2['location'])

In [13]:
data_2.head(5)

,location,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,58,0,0,0,0,0,-78,0,0,0,0,0,0,0
1,63,0,0,0,0,0,-78,0,0,0,0,0,0,0
2,63,0,0,0,0,0,-77,0,0,0,0,0,0,0
3,63,0,0,0,0,0,-77,0,0,0,0,0,0,0
4,63,0,0,0,0,0,-77,0,0,0,0,0,0,0

### Step 3 将数据集分成训练集和测试集

In [14]:
features = data_2

In [15]:
n_features = features.drop('location', axis=1)
n_samples = features['location']

In [16]:
X_train, X_test,y_train,y_test = train_test_split(n_features,n_samples,test_size=0.2)

### Step 4  运用算法实现多分类问题，预测location的位置

### Way-1: SVM (Multi-class)

In [17]:
from sklearn import svm
clf = svm.SVC(gamma='auto', decision_function_shape='ovo')
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
y_pred = clf.predict(X_test)
print(y_pred)

[ 61  23  61  18  72  54  72  45  54  30  40  21 104  47  30  30  83  13
  61  20  49   6  29  39  72  94  59  61 100  13  72  11  40  12  21  20
  20  86  13  36  72  23  84  40  47  14  38  22  23  34  31  36  60  83
  49  54  83  20  13  20  60  12  33  13  30  31  22  83  94 104  16  23
  30  31  23  29  83  33  73  83  22  13  11  59  30  94  83  11  55  30
   6  83  47   2   6  40   6  54  22  20 102  30  72  30  10  10  10  83
  33  83  29  31  56  40  83  24  12  50  10 104  12  12  16  10  55  72
  82  30  22  73   7  52  14  43  34  11  61 100  72  82  13  31  56  36
  83  45  44  72  72  20  12  72  49  55 100  72  94  47  83  29  46  39
  69  74  72  11 104  54  30  82  88  13  49  12  29 104 100   2  54  39
  30  83  88  72  13  30  83   6  30  80  59  40  13  37  20  86  83  61
  83  94  36  83  36 100  10  30  29  66  36  31  72  38  40  72  37  66
  66  13  88  96 100  83  13  10 100   6  83  40  16  82  40  29  25   2
  73  61  60  12  38  62  60  53  44  72  83 100  30  28  20  72  13  39
  30  29  88  43  31  66  83  49  65  22   6  11  88  31  11  61  20  31
  83  86  16  12  72 100  19  83  72  45  72  47  40  72]

In [19]:
#查看准确度Accuracy,Precission,Recall
from sklearn import metrics

accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred,average='micro')
recall = metrics.recall_score(y_test, y_pred,average='micro')

In [20]:
print("SVM:the accuracy is: ",accuracy)
print("SVM:the precision is: ",precision)
print("SVM:the recall is: ",recall)

SVM:the accuracy is:  0.3028169014084507
SVM:the precision is:  0.3028169014084507
SVM:the recall is:  0.3028169014084507

### Way-2: Decision Tree

In [21]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [22]:
y_pred = clf.predict(X_test)
print(y_pred)

[ 61  23  61  47  72  54  72  35  54   7  40  21 104  44   8   7  61  22
  61  20  49  31  64  39  83  74  59  61  87  38  86  11  49  12  21  20
  20  86  48  27  83  23  61   8  47  14   9  11  23  40  47  17  60  76
  40  54  74  20  23  20  60  23  33  80  37   7  22  76  94 104   5  22
  30   7  29  18  61  34  73  83  22  59  11  72  20  74  76  11  55  30
  18  74  44   2  31  32  18  54  39  20 102  30  72  30  22   7  22  76
  32  74  29  31  43  40  76  24  12  50   7  96  12  42  16   9  55  72
  82  30  23  73  31  68  14  43  32  11  61 101  72  82  11  47  56  36
  76  45  44  83  72  20  23  72  49  55 101  83  74  44  76  29  46  39
  69  74  72  11 104  54   7  82  88  16  40  23  64 104 101   2  54  39
  30  61  81  72  13   9  61   6  30  80  44   7  80  37  20  86  74  61
  76  74  17  76  27 101   9   7  29  31  36  47  83  18   7  72  37  31
  31  13  88  96  87  76  38   7 101  18  61   7  16  82  40  45  15   2
  73  61  60  12   9  49  60  53  44  72  76  87  30  28  20  72  13  50
  30  17  88  43  18  37  74  49  65  22   6  22  88  47  13  67  20  47
  76  86  16  23  72 101  30  61  83  39  72  44  23  72]

In [23]:
from sklearn import metrics

accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred,average='micro')
recall = metrics.recall_score(y_test, y_pred,average='micro')

In [24]:
print("Decision Tree:the accuracy is: ",accuracy)
print("Decision Tree:the precision is: ",precision)
print("Decision Tree:the recall is: ",recall)

Decision Tree:the accuracy is:  0.28169014084507044
Decision Tree:the precision is:  0.28169014084507044
Decision Tree:the recall is:  0.28169014084507044

### Way-3: Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [26]:
clf = RandomForestClassifier(n_estimators=100, max_depth=10,
                             random_state=1)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [27]:
y_pred = clf.predict(X_test)
print(y_pred)

[ 61  23  61  30  83  54  83  51  54  30  40  21 104  44  30  30  83  13
  61  20  62   6  29  39  83  94  72  61  87  31  72  11  40  12  21  20
  20  86  58  36  83  23  83  40  47  14  30  11  23  40   6  54  60  83
  49  54  83  20  13  20  60  23  33  80  30  31  22  83  94 104   5  22
  30  31  23  29  83  33  73  83  12  59  11  72  20  94  83  11  55  30
  31  83  44   2   6  49  31  54  22  20 102  30  83  30  10  10  10  83
  32  83  29  31  43  40  83  24  12  50  10  96  12  12  16  29  55  83
  82  30  22  73   7  52  14  43  34  11  61  61  83  82  37   6  56  36
  83  45  44  83  83  20  23  83  62  55  61  83  94  44  83  29  46  39
  69  74  83  11 104  54  30  82  88  16  49  23  29 104  61   2  54  39
  30  83  88  83  13  30  83   6  30  80  51  40  80  37  20  86  83  61
  83  94  54  83  36  61  29  30  29  66  36   6  83  30  40  83  37  66
  66  13  88  96  87  83  31  10  61  31  83  40  16  82  40  45  15   2
  73  61  60  12  30  49  60  53  44  83  83  87  30  29  20  83  13  62
  30  29  88  43  31  66  83  62  65  22   6  11  88   6  11  67  20   6
  83  86  16  23  83  61  30  83  83  45  83  44  40  83]

In [29]:
from sklearn import metrics

accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred,average='micro')
recall = metrics.recall_score(y_test, y_pred,average='micro')

In [30]:
print("Random Tree:the accuracy is: ",accuracy)
print("Random Tree:the precision is: ",precision)
print("Random Tree:the recall is: ",recall)

Random Tree:the accuracy is:  0.30985915492957744
Random Tree:the precision is:  0.30985915492957744
Random Tree:the recall is:  0.30985915492957744